packages:
  - 'packages/*'

allowBuilds:
  esbuild: true
  msw: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@book000/*'
patchedDependencies: { drizzle-orm@0.45.2: patches/drizzle-orm@0.45.2.patch }
